apiVersion: v1
kind: Pod
metadata:
  name: static-site
  labels:
    app: static-site
spec:
  containers:
    - name: static-site
      image: ncomeau/demo
      ports:
      - containerPort: 80
        hostPort: 80
        name: static-site
