apiVersion: v1
kind: Pod
metadata:
  name: static-site
  labels:
    app: static-site
spec:
  containers:
    - name: static-site
      image: ncomeau/demo
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"      
      ports:
      - containerPort: 80
        hostPort: 80
        name: static-site

---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: static-service
spec:
  selector:
    app: static-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort
