apiVersion: v1
kind: Pod
metadata:
  name: static-site
  labels:
    app: static-site
spec:
  hostNetwork: true
  containers:
    - name: static-site
      image: ncomeau/demo
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
      - containerPort: 80
        hostPort: 80
        name: static-site

